jobs/urls.py
from django.urls import path

from . import views

# URL для этих путей /jobs/...

urlpatterns = [
    
    # URL для API
    
    path('api/skills/all/', views.all_skills, name='all_skills'),

    path('api/jobs/search/', views.search_jobs, name='search_jobs'),
    path('api/jobs/all/', views.all_jobs, name='all_jobs'),
    path('api/jobs/<int:pk>/', views.JobDetail.as_view(), name='job-detail'),
    
    path('api/responses/<int:pk>/', views.all_responses, name='all_responses'),
    path('api/responses/<int:pk>/detail', views.ResponseDetail.as_view(), name='response-detail'),
    
    path('api/features/<int:pk>/', views.all_features, name='feature-detail'),
    path('api/features/<int:pk>/search/', views.search_features, name='feature-detail'),
    
    # URL для Django

    path('responses/', views.responses_list_view, name='responses_list_view'),
    path('features/', views.features_list_view, name='features_list_view'),
    path('myresps/', views.my_resps_view, name='my_resps'),

    path('create/job/', views.create_job, name='create_job'),
    path('delete/job/<int:job_id>/', views.delete_job, name='delete_job'),
    path('view/job/<int:job_id>/', views.job_detail_view, name='job_detail_view'),
    
    path('create/response/<int:job_id>/', views.response_create_view, name='job_response_view'),
    
    path('resp/accept/<int:response_id>/', views.accept_resp, name="accept_resp"),
    path('resp/reject/<int:response_id>/', views.reject_resp, name="reject_resp"),
    
    path('create/feature/<int:job_id>/', views.feature_create_view, name='job_feature_view'),
    path('delete/feature/<int:job_id>/', views.feature_delete, name='feature_delete_view'),
]

proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from manager.views import *

urlpatterns = [
    path('', main_view, name='main'),
    path('vacancies/', home_view, name='home'),
    path('admin/', admin.site.urls),
    
    # Приложение Users
    path('users/', include('users.urls')),
    # Приложение Jobs
    path('jobs/', include('jobs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

# URL для этих путей /users/...

urlpatterns = [
    
    # URL для API
    
    path('api/users/all/', views.all_users, name='users-list'),
    path('api/users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
    
    path('api/seekers/all/', views.all_seekers, name='seekers-list'),
    path('api/seekers/<int:pk>/', views.JobSeekerDetail.as_view(), name='seeker-detail'),
    
    path('api/employers/all/', views.all_employers, name='employers-list'),
    path('api/employers/<int:pk>/', views.EmployerDetail.as_view(), name='employer-detail'),

    # URL для Django

    path('set_user_type/<str:user_type>/', views.set_user_type, name='set_user_type'),
    path('review/<int:pk>/', views.company_review, name='company_review'),
    
    path('view/company/<int:pk>/', views.company_profile, name='company_profile'),
    path('view/seeker/<int:pk>/', views.seeker_profile, name='seeker_profile'),

    path('signup/employer/', views.employer_signup, name='employer_signup'),
    path('signup/seeker/', views.job_seeker_signup, name='job_seeker_signup'),
    
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
]

users/models.py
from decimal import Decimal

from django.db import models
from django.contrib.auth.models import AbstractUser

from manager.models import Skill


class User(AbstractUser):
    USER_TYPE_CHOICES = (
        ('employer', 'Работодатель'),
        ('seeker', 'Соискатель'),
    )
    region = models.CharField(verbose_name='Регион', max_length=255, blank=True, null=True, default='')
    country = models.CharField(verbose_name='Страна',max_length=255, blank=True, null=True, default='')
    phone_number = models.CharField(verbose_name='Номер телефона', max_length=20, blank=True, null=True, default='')
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, default=USER_TYPE_CHOICES[0][1])
    date_of_registration = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True, verbose_name="Фотография профиля")


class Employer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='employer_profile')
    company_name = models.CharField(max_length=100, verbose_name="Наименование компании")
    inn = models.CharField(max_length=255, verbose_name="ИНН")
    industry = models.CharField(max_length=255, verbose_name="Отрасль")
    company_address = models.CharField(verbose_name='Адрес компании', max_length=255, blank=True, null=True)
    website = models.URLField(verbose_name='Сайт', blank=True, null=True)
    rating = models.FloatField(verbose_name="Рейтинг", default=.0)

    company_description = models.TextField(verbose_name="Описание компании", blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.company_name}"


class JobSeeker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='jobseeker_profile')
    full_name = models.CharField(verbose_name="ФИО", max_length=255)
    # skills = models.TextField(verbose_name="Навыки", blank=True, null=True)
    skills = models.ManyToManyField(Skill, related_name='users', blank=False)
    education = models.CharField(max_length=255, verbose_name="Образование")
    experience = models.TextField(verbose_name="Опыт работы", blank=True, null=True)
    
    desired_job_type = models.CharField(max_length=255, verbose_name="Желаемая категория работы", blank=True, null=True)
    desired_salary = models.CharField(max_length=50, verbose_name="Ожидаемая зарплата", blank=True, null=True)
    desired_location = models.CharField(max_length=100, verbose_name="Желаемое место работы", blank=True, null=True)
    
    portfolio_link = models.URLField(verbose_name="Ссылка на портфолио", blank=True, null=True)
    languages = models.TextField(verbose_name="Языки во владении", blank=True, null=True)
    interests = models.TextField(verbose_name="Интересы", blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}"
    

class Review(models.Model):
    RATING_CHOICES = [
        (1, 'Отвратительно'),
        (2, 'Плохо'),
        (3, 'Средне'),
        (4, 'Хорошо'),
        (5, 'Отлично'),
    ]
    
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='emp')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='us')
    date_of_creation = models.DateTimeField(verbose_name='Дата отзыва', auto_now_add=True)
    rate = models.IntegerField(choices=RATING_CHOICES, verbose_name='Оценка')
    message = models.TextField(verbose_name="Отзыв", blank=True, null=True)


class Notification(models.Model):
    destination = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dest')
    message = models.TextField(verbose_name="Уведомление", blank=True, null=True)
    is_checked = models.BooleanField(verbose_name="Просмотрена", default=False)

users/views.py
import pdb
from django.db.models import Avg
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from rest_framework.decorators import api_view
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.response import Response

from jobs.models import Job
from .forms import UserReviewForm, EmployerSignUpForm, JobSeekerSignUpForm, UserProfileForm, SeekerProfileForm, EmployerProfileForm, UserLoginForm
from .serializers import EmployerSerializer, JobSeekerSerializer, UserSerializer
from .models import JobSeeker, Employer, User, Review
from jobs.models import Response as resp


#-----------------
# Отзыв о компании
#-----------------


def company_review(request, pk):
    
    employer = get_object_or_404(Employer, user__id=pk)
    reviews = Review.objects.filter(employer=employer)
    
    context = {
        'user_type': request.session.get('user_type'),
        'reviews': reviews,
        'reviews_count': reviews.count(),
    }

    if not request.user.is_authenticated:
        return redirect('home')

    try:
        existing_review = Review.objects.get(employer=employer, user=request.user)
    except Review.DoesNotExist:
        existing_review = None
    
    if request.method == 'POST':
        form = UserReviewForm(request.POST, instance=existing_review)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.employer = employer
            review.save()
            if reviews.exists():
                avg_rating = reviews.aggregate(avg=Avg('rate'))['avg']
                if avg_rating is not None:
                    employer.rating = avg_rating
            employer.save()
            return redirect(f'/users/view/company/{pk}')
    else:
        form = UserReviewForm(instance=existing_review)
    
    context['employer'] = employer
    context['form'] = form
    return render(request, 'users/review.html', context)


# -------------------------
# Регистрация и авторизация
# -------------------------


def set_user_type(request, user_type):
    logout(request)
    request.session['user_type'] = user_type
    return redirect('main')


def employer_signup(request):
    context = {
        'user_type': request.session.get('user_type'),
    }
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = EmployerSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = EmployerSignUpForm()

    context['form'] = form
    return render(request, 'users/register.html', context)


def job_seeker_signup(request):
    context = {
        'user_type': request.session.get('user_type'),
    }
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = JobSeekerSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = JobSeekerSignUpForm()

    context['form'] = form
    return render(request, 'users/register.html', context)


def login_view(request):
    context = {
        'user_type': request.session.get('user_type'),
    }
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            print(1)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                context['user_type'] = request.user.user_type
                print(context['user_type'])
                return redirect('home')
            else:
                form.add_error(None, 'Неверное имя пользователя или пароль.')
    else:
        form = UserLoginForm()

    context['form'] = form
    return render(request, 'users/login.html', context)


# ---------------
# Профиль и выход
# ---------------


@login_required
def profile_view(request):
    
    user = request.user
    user_form = UserProfileForm(request.POST or None, request.FILES or None, instance=user)
    seeker_form = SeekerProfileForm(request.POST or None, instance=user.jobseeker_profile) if hasattr(user, 'jobseeker_profile') else None
    employer_form = EmployerProfileForm(request.POST or None, instance=user.employer_profile) if hasattr(user, 'employer_profile') else None
    employer = get_object_or_404(Employer, user=request.user) if hasattr(user, 'employer_profile') else None

    context = {
        'user_type': request.session.get('user_type'),
        'user_form': user_form,
        'seeker_form': seeker_form,
        'employer_form': employer_form,
        'employer': employer,
        'reviews_count': Review.objects.filter(employer=employer).count() if hasattr(user, 'employer_profile') else None,
    }

    if user.user_type == User.USER_TYPE_CHOICES[1][0]:
        context['skills'] = user.jobseeker_profile.skills.all()

    if request.method == 'POST':
        forms_valid = user_form.is_valid()
        if user.user_type == User.USER_TYPE_CHOICES[0][0] and seeker_form:
            forms_valid = forms_valid and seeker_form.is_valid()
        elif user.user_type == User.USER_TYPE_CHOICES[1][0] and employer_form:
            forms_valid = forms_valid and employer_form.is_valid()

        if forms_valid:
            user_form.save()
            if seeker_form:
                seeker_form.save()
            elif employer_form:
                employer_form.save()
            return redirect('profile')

    return render(request, 'users/profile.html', context)


def logout_view(request):
    logout(request)
    request.session['user_type'] = 'seeker'
    return redirect('/')


def company_profile(request, pk):
    context = {
        'user_type': request.session.get('user_type'),
    }
    company = get_object_or_404(Employer, pk=pk)
    reviews = Review.objects.filter(employer=company)
    jobs = Job.objects.filter(employer=company)
    
    context['employer'] = company
    context['reviews'] = reviews
    context['reviews_count'] = reviews.count()
    context['jobs_count'] = jobs.count()

    return render(request, 'users/company-profile.html', context)


def seeker_profile(request, pk):
    context = {
        'user_type': request.session.get('user_type'),
    }
    seeker = get_object_or_404(Employer, pk=pk)
    resps = resp.objects.filter(job_seeker=seeker)
    
    context['seeker'] = seeker
    context['resps'] = resps
    context['resps_count'] = resps.count()

    return render(request, 'users/seeker-profile.html', context)


# -------------
# Views для API
# -------------


class JobSeekerDetail(RetrieveUpdateDestroyAPIView):
    queryset = JobSeeker.objects.all()
    serializer_class = JobSeekerSerializer

@api_view(['GET'])
def all_seekers(request):
    seekers = JobSeeker.objects.all()
    serializer = JobSeekerSerializer(seekers, many=True)
    return Response(serializer.data)


class EmployerDetail(RetrieveUpdateDestroyAPIView):
    queryset = Employer.objects.all()
    serializer_class = EmployerSerializer

@api_view(['GET'])
def all_employers(request):
    employers = Employer.objects.all()
    serializer = EmployerSerializer(employers, many=True)
    return Response(serializer.data)


class UserDetail(RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

@api_view(['GET'])
def all_users(request):
    users = User.objects.all()
    serializer = UserSerializer(users, many=True)
    return Response(serializer.data)

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="icon" href="{% static 'users/images/hhrubsk-logo.png' %}"></link>
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-solid-straight/css/uicons-solid-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-bold-rounded/css/uicons-bold-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-solid-rounded/css/uicons-solid-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-solid-rounded/css/uicons-solid-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-bold-straight/css/uicons-bold-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-thin-straight/css/uicons-thin-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-straight/css/uicons-regular-straight.css'>
    
    {% block additionals %}
    {% endblock %}
    
</head>
<body>
    <header class="header-top">
        <div class="container" style="margin-bottom: 0;margin-top: 0;padding-top: 0;padding-bottom: 0;">
            <nav class="top-panel">
                <ul class="nav-links">
                    <li><a class="nav-link {% if user_type == 'seeker' %}sel{% endif %}" href="{% if not user_type == 'seeker' %}{% url 'set_user_type' 'seeker' %}{% endif %}" id="job-seeker-btn" href="#">Соискатель</a></li>
                    <li><a class="nav-link {% if user_type == 'employer' %}sel{% endif %}" href="{% if not user_type == 'employer' %}{% url 'set_user_type' 'employer' %}{% endif %}" id="employer-btn" href="#">Работодатель</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'features_list_view' %}">Избранное</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    
    <div style="padding: 10px 0;background: #1d1d1d;">
        <div class="container" style="margin: 0 auto;padding: 0 20px;">
            <div style="justify-content: space-between;display: flex;">
                <div style="display: flex;align-items: center;justify-content: center;gap: 24px;">
                    <div>
                        <img src="/static/users/images/hhrubsk-logo.png" style=" height: 64px;">
                    </div>
                    <a class="sub-link" href="{% url 'main' %}">Главная</a>
                    <a class="sub-link" href="{% url 'home' %}">Все вакансии</a>
                    {% if user.is_authenticated and not user.is_superuser%}
                        {% if user.user_type == 'employer' %}
                            <a class="sub-link" href="{% url 'responses_list_view' %}">Отклики</a>
                            <a class="sub-link" href="{% url 'create_job' %}">Создать вакансию</a>
                        {% else %}
                            <a class="sub-link" href="{% url 'my_resps' %}">Мои отклики</a>
                        {% endif %}
                    {% endif %}
                    <span class="sub-link">Помощь</span>
                </div>
                 <div class="btns-block">
                {% if not user.is_authenticated %}
                    <a class="btn btn-invert" id="register-btn" href="{% if user_type == 'employer' %}{% url 'employer_signup' %}{% else %}{% url 'job_seeker_signup' %}{% endif %}" style="border-radius: 4rem;">Зарегистрироваться</span>
                    <a class="btn learn-more" href="{% url 'login' %}" style="border-radius: 4rem;">Войти</a></div>
                {% else %}
                    <a class="nav-link" href="{% url 'profile' %}">
                        <span class="user-name" style="color: #ffffff;font-weight: 600;font-size: 18px;font-family: 'Helvetica';">{{ user.username }}</span>
                        {% if user.profile_picture %}
                            <img class="user-avatar" src="{{ user.profile_picture.url }}" alt="Фото профиля">
                        {% else %}
                            <img class="user-avatar" src="{% static 'users/images/user_avatar_default.png' %}" alt="Фото профиля">
                    {% endif %}
                    </a>
                    <a href="#" class="bell-notes">
                        <i class="fi fi-ss-bell"></i>
                        <i class="fi fi-rr-bell"></i>
                        <div style="width: 12px;height: 12px;border-radius: 32px;top: 16px;right: 20px;position: absolute;background: red;"></div>
                    </a>
                {% endif %}
                </div>
            </div>
        </div>
    </div>

    <main class="main">
        {% block content %}
        {% endblock %}
    </main>
    
    <div class="footer">
        <div class="container">
            &copy; 2024 HeadHunter. Все права защищены.
        </div>
    </div>
    
    {% block bottom_additionals %}
    {% endblock %}

</body>
</html>

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}
  Профиль | 
  {% if user.user_type == 'employer' %}
  Работодателя
  {% elif user.user_type == 'seeker' %}
  Соискателя
  {% endif %}
{% endblock %}

{% block additionals %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">

<style>
@import url('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js');
@import url('https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css');
@import url('https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js');

body{
  background-color: #e2e8f0;
}

#id_profile_picture{
  text-align-last: center;
}

.form-control:focus {
    box-shadow: none;
    border-color: #16A3FF;
}

.btn-primary {
  box-shadow: none;
  padding: 12px 16px;
  background: #16A3FF;
  border: 2px solid #16A3FF;
  border-radius: 4rem;
  color: #fff;
  font-weight: 600;
  font-size: 18px;
  margin: 16px 0;
  cursor: pointer;
  transition: all .3s;
  text-decoration: none !important;
}

.btn-primary:hover {
  background: transparent !important;
  color: #16A3FF !important;
  border-color: #16A3FF!important;
}

.rounded-circle{
  width: 150px;
  height: 150px;
}

.btn-exit{
  background-color: transparent;
  border-color: #ff4646;
  color: #ff4646;
  box-shadow: none;
  padding: 12px 16px;
  border-radius: 4rem;
  font-weight: 600;
  font-size: 18px;
  margin: 16px 0;
  cursor: pointer;
  transition: all .3s;
  text-decoration: none !important;
}

.btn-exit:hover{
  background-color: #ff4646 !important;
  color: #fff !important;
}

.back:hover {
    color: #16A3FF;
    cursor: pointer
}

.labels {
    font-size: 11px
}

.add-experience:hover {
    background: #16A3FF;
    color: #fff;
    cursor: pointer;
    border: solid 1px #16A3FF
}
</style>
{% endblock %}

{% block content %}
  <div class="container rounded bg-white mt-5 mb-5">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
              {% if user.profile_picture %}
                <img class="rounded-circle mt-5" width="150px" src="{{ user.profile_picture.url }}" alt="Фото профиля">
              {% else %}
                <img class="rounded-circle mt-5" width="150px" src="{% static 'users/images/user_avatar_default.png' %}" alt="Фото профиля">
              {% endif %}
              <span class="font-weight-bold">{{user.username}}</span>
              <span class="text-black-50">Время захода<br>{{user.last_login}}</span>
              {% if user.user_type == 'employer' %}
              <p class="comp-rating">
                <span style="display: flex;gap: 4px;">
                  <span class="star"></span>
                  <span class="star"></span>
                  <span class="star"></span>
                  <span class="star"></span>
                  <span class="star"></span>
                </span>
                <span id="reviews-quantity" style="font-size: 14px;display: flex;align-items: center;"></span>
                <script>
                  var companyRating = parseFloat('{{ employer.rating }}'.replace(',', '.'));
                  var revCount = parseInt('{{reviews_count}}');
                  var stars = document.getElementsByClassName("star");
                  count = document.getElementById("reviews-quantity");
                  
                  if (companyRating){
                    count.textContent = `(${companyRating.toFixed(2)}) ${revCount} отз.`;
                  }
                  else {
                    count.textContent = "Нет отзывов";
                  }

                  Array.from(stars).forEach((star, index) => {
                      if (companyRating >= index + 1) {
                          // Полная звезда
                          star.innerHTML = `<i class="fi fi-ss-star" style="color: orange;"></i>`;
                      } else if (companyRating > index && companyRating < index + 1) {
                          // Половина звезды
                          star.innerHTML += `<i class="fi fi-ss-star"></i>`;
                          star.innerHTML += `<i class="fi fi-ss-star-sharp-half" style="color: orange;"></i>`;
                      } else {
                        // Пустая звезда
                        star.innerHTML = `<i class="fi fi-ss-star"></i>`;
                      }
                  });
              </script>
              </p>
              {% endif %}
            </div>
              {{user_form.profile_picture}}
              {% if user.user_type == 'seeker' %} 
                <p class="description" style="justify-content: center;margin-top: 32px;-webkit-line-clamp: unset;display: flex;gap: 16px;flex-wrap: wrap;">
                  {% for skill in skills %}
                    <span class="alt-info">{{skill.name}}</span>
                  {% endfor %}
                </p>
            {% endif %}
            </div>
            <div class="col-md-5 border-right">
              <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Настройки профиля 
                    {%if not user.is_superuser %}
                      {% if user.user_type == 'seeker' %} 
                      <span>соискателя</span>
                      {% elif user.user_type == 'employer' %}
                      <span>работодателя</span>
                      {% endif %}
                    {% endif %}
                    </h4>
                </div>
                  <div class="row mt-2">
                      <div class="col-md-6"><label class="labels">Логин</label>{{ user_form.username }}</div>
                      <div class="col-md-6"><label class="labels">Пароль</label>{{ user_form.password }}</div>
                  </div>
                  <div class="row mt-3">
                    <div class="col-md-6"><label class="labels">Страна</label>{{ user_form.country }}</div>
                    <div class="col-md-6"><label class="labels">Регион/Город</label>{{user_form.region}}</div>
                  </div>
                  <div class="row mt-3">
                      <div class="col-md-12"><label class="labels">Номер телефона</label>{{user_form.phone_number}}</div>
                      <div class="col-md-12"><label class="labels">Почтовый ящик</label>{{user_form.email}}</div>
                      {% if not user.is_superuser %}
                        {% if user.user_type == 'seeker' %}
                          <div class="col-md-12"><label class="labels">Образование</label>{{seeker_form.education}}</div>
                          <div class="col-md-12"><label class="labels">Опыт работы</label>{{seeker_form.experience}}</div>
                          <div class="col-md-12"><label class="labels">Навыки</label>{{seeker_form.skills}}</div>
                          <div class="col-md-12"><label class="labels">Желаемая категория работы</label>{{seeker_form.desired_job_type}}</div>
                          <div class="col-md-12"><label class="labels">Желаемая заработная плата</label>{{seeker_form.desired_salary}}</div>
                          <div class="col-md-12"><label class="labels">Желаемое место работы</label>{{seeker_form.desired_location}}</div>
                          <div class="col-md-12"><label class="labels">Ссылка на ваше портфолио</label>{{seeker_form.portfolio_link}}</div>
                          <div class="col-md-12"><label class="labels">Языки во владении</label>{{seeker_form.languages}}</div>
                          <div class="col-md-12"><label class="labels">Интересы</label>{{seeker_form.interests}}</div>
                        {% elif user.user_type == 'employer' %}
                          <div class="col-md-12"><label class="labels">Название компании</label>{{employer_form.company_name}}</div>
                          <div class="col-md-12"><label class="labels">ИНН</label>{{employer_form.inn}}</div>
                          <div class="col-md-12"><label class="labels">Отрасль</label>{{employer_form.industry}}</div>
                          <div class="col-md-12"><label class="labels">Адрес</label>{{employer_form.company_address}}</div>
                          <div class="col-md-12"><label class="labels">Сайт</label>{{employer_form.website}}</div>
                          <div class="col-md-12"><label class="labels">Описание</label>{{employer_form.company_description}}</div>
                        {% endif %}
                      {% endif %}
                  </div>
                  <div class="mt-5 text-center" style="display: flex;justify-content: center;gap: 12px;">
                    <button class="btn btn-primary profile-button" type="submit">Сохранить изменения</button>
                    <a class="btn btn-exit" href="{% url 'logout' %}">Выйти</a>
                  </div>
            </div>
        </div>
        <div class="col-md-4" style="display: none;">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center experience"><span>Edit Experience</span><span class="border px-3 p-1 add-experience"><i class="fa fa-plus"></i>&nbsp;Experience</span></div><br>
                <div class="col-md-12"><label class="labels">Experience in Designing</label><input type="text" class="form-control" placeholder="experience" value=""></div> <br>
                <div class="col-md-12"><label class="labels">Additional Details</label><input type="text" class="form-control" placeholder="additional details" value=""></div>
            </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}