jobs/urls.py
from django.urls import path

from . import views

# URL для этих путей /jobs/...

urlpatterns = [
    
    # URL для API
    
    path('api/skills/all/', views.all_skills, name='all_skills'),

    path('api/jobs/search/', views.search_jobs, name='search_jobs'),
    path('api/jobs/all/', views.all_jobs, name='all_jobs'),
    path('api/jobs/<int:pk>/', views.JobDetail.as_view(), name='job-detail'),
    
    path('api/responses/<int:pk>/', views.all_responses, name='all_responses'),
    path('api/responses/<int:pk>/detail', views.ResponseDetail.as_view(), name='response-detail'),
    
    path('api/features/<int:pk>/', views.all_features, name='feature-detail'),
    path('api/features/<int:pk>/search/', views.search_features, name='feature-detail'),
    
    # URL для Django

    path('responses/', views.responses_list_view, name='responses_list_view'),
    path('features/', views.features_list_view, name='features_list_view'),
    path('myresps/', views.my_resps_view, name='my_resps'),

    path('create/job/', views.create_job, name='create_job'),
    path('delete/job/<int:job_id>/', views.delete_job, name='delete_job'),
    path('view/job/<int:job_id>/', views.job_detail_view, name='job_detail_view'),
    
    path('create/response/<int:job_id>/', views.response_create_view, name='job_response_view'),
    
    path('resp/accept/<int:response_id>/', views.accept_resp, name="accept_resp"),
    path('resp/reject/<int:response_id>/', views.reject_resp, name="reject_resp"),
    
    path('create/feature/<int:job_id>/', views.feature_create_view, name='job_feature_view'),
    path('delete/feature/<int:job_id>/', views.feature_delete, name='feature_delete_view'),
]

proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from manager.views import *

urlpatterns = [
    path('', main_view, name='main'),
    path('vacancies/', home_view, name='home'),
    path('admin/', admin.site.urls),
    
    # Приложение Users
    path('users/', include('users.urls')),
    # Приложение Jobs
    path('jobs/', include('jobs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

from users.models import Employer, JobSeeker, User
from manager.models import Skill

class Job(models.Model):

    JOB_TYPE_CHOICES = (
        ('it', 'IT'),
        ('hr', 'HR'),
        ('finance', 'Финансы'),
        ('marketing', 'Маркетинг'),
        ('trade', 'Торговля'),
    )

    JOB_EMPLOYMENT_TYPE = (
        ('full', 'Полная занятость'),
        ('half', 'Неполная занятость'),
        ('free', 'Удаленно'),
    )

    title = models.CharField(verbose_name="Наименование вакансии", max_length=255)
    industry = models.CharField(max_length=20, choices=JOB_TYPE_CHOICES, verbose_name="Категория")
    employer = models.ForeignKey(Employer, verbose_name="Работодатель", on_delete=models.CASCADE, related_name='empl')
    skills = models.ManyToManyField(Skill, related_name='vacancies', blank=False)
    salary = models.CharField(verbose_name="Зарплата", max_length=255)

    work_exp = models.CharField(verbose_name="Опыт работы", max_length=32, blank=True, null=True)
    contact_email = models.EmailField(verbose_name="Контактный Email", blank=True)
    location = models.CharField(verbose_name="Место (Адрес)", max_length=255)
    description = models.TextField(verbose_name="Описание")
    
    employment_type = models.CharField(verbose_name="Тип занятости", choices=JOB_EMPLOYMENT_TYPE, max_length=50, default='full')
    resps = models.BigIntegerField(verbose_name="Кол-во откликов", default=0)
    date_of_creation = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)

    def __str__(self):
        return f"[{self.employer.company_name}] {self.title}"

    def get_absolute_url(self):
        return reverse('job_detail', args=[str(self.id)])
    

class Response(models.Model):

    STATUS_CHOICES = [('pending', 'На рассмотрении'), ('accepted', 'Одобрено'), ('rejected', 'Отклонено')]

    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='responses')
    job_seeker = models.ForeignKey(JobSeeker, on_delete=models.CASCADE, related_name='seeker')
    date_of_response = models.DateTimeField(verbose_name='Дата отклика', auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    class Meta:
        unique_together = ('job', 'job_seeker')

    def __str__(self):
        return f"{self.job_seeker.user.username} {self.job.title}"
    
    
class Feature(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='feature_job')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feature')
    

jobs/forms.py
from .models import Job
from django import forms


# ---------------------------
# Форма для создания вакансии
# ---------------------------


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = [
            'title',
            'industry',
            'skills',
            'salary',
            'contact_email',
            'location',
            'employment_type',
            'work_exp',
            'description',
        ]
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Заголовок вакансии'}),
            'industry': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Выберите отрасль'}),
            'skills': forms.SelectMultiple(attrs={'id':'multiSelect','name':'multiSelect', 'class': 'form-control', 'placeholder': 'Выберите навыки', 'data-coreui-search':'true',}),
            'salary': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Заработная плата'}),
            'contact_email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Контактный адрес почты'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Место поиска'}),
            'employment_type': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Тип занятости'}),
            'work_exp': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Требуемый опыт работы'}),
            'description': forms.Textarea(attrs={'rows': 4, 'class': 'form-control', 'placeholder': 'Описание для вакансии'}),
        }

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['industry'].empty_label = "Выберите категорию"
        self.fields['industry'].widget.attrs['class'] += ' select-placeholder'
        
        self.fields['employment_type'].empty_label = "Выберите тип занятости"
        self.fields['employment_type'].widget.attrs['class'] += ' select-placeholder'

jobs/views.py
import json

from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.db.models import Q
from django.http import HttpResponseRedirect

from rest_framework.decorators import api_view
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.response import Response
from rest_framework import generics

from users.forms import EmployerSignUpForm

from .forms import JobForm
from .serializers import JobSerializer, ResponseSerializer, FeatureSerializer, SkillsSerializer
from .models import Feature, Skill, Job, Response as resp
from users.models import Review

# -------------------------------------
# Создание/удаление и просмотр вакансии
# -------------------------------------


def create_job(request):
    if request.user.is_authenticated and request.user.user_type == 'employer':
        if request.method == 'POST':
            form = JobForm(request.POST)
            if form.is_valid():
                job = form.save(commit=False)
                job.employer = request.user.employer_profile
                job.save()
                form.save_m2m()
                return redirect('home')
        else:
            form = JobForm()
        return render(request, 'jobs/job-creation.html', {'form': form})
  
    context = {
        'user_type': request.session.get('user_type'),
    }
    
    if request.method == 'POST':
        form = EmployerSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = EmployerSignUpForm()

    context['form'] = form
    return render(request, 'users/register.html', context)


def delete_job(request, job_id):
    if request.user.is_authenticated and request.user.user_type == 'employer':
        job = get_object_or_404(Job, id=job_id, employer=request.user.employer_profile)
        job.delete()
    return redirect('home')


def job_detail_view(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    is_featured = Feature.objects.filter(job=job, user=request.user).first() if request.user.is_authenticated else False
    is_you = job.employer.user == request.user
    context = {
        'is_you':is_you,
        'job': job,
        'is_featured':is_featured,
        'skills': job.skills.all(),
        'user_type': request.session.get('user_type'),
    }
    
    reviews = Review.objects.filter(employer=job.employer)
    jobs = Job.objects.filter(employer=job.employer)
    
    context['employer'] = job.employer
    context['reviews'] = reviews
    context['reviews_count'] = reviews.count()
    context['jobs_count'] = jobs.count()

    if request.user.is_authenticated and request.user.user_type == 'seeker':
        context['responded'] = resp.objects.filter(job=job, job_seeker__user=request.user).first()

    return render(request, 'jobs/job-details.html', context)


# ------------------
# Отклик на вакансию
# ------------------


@login_required
def response_create_view(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    is_job_seeker = hasattr(request.user, 'jobseeker_profile')
    user_already_applied = False

    if is_job_seeker:
        user_already_applied = resp.objects.filter(job=job, job_seeker=request.user.jobseeker_profile).exists()

    if is_job_seeker:
        job_seeker_profile = request.user.jobseeker_profile
        if not user_already_applied:
            resp.objects.create(job=job, job_seeker=job_seeker_profile)
            job.resps += 1
            job.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def accept_resp(request, response_id):
    if request.user.user_type == 'employer':
        res = get_object_or_404(resp, id=response_id)
        if res.status == res.STATUS_CHOICES[0][0] and res.job.employer.user == request.user:
            res.status = res.STATUS_CHOICES[1][0]
            res.save()
        return redirect('responses_list_view')
    return redirect('home')


@login_required
def reject_resp(request, response_id):
    if request.user.user_type == 'employer':
        res = get_object_or_404(resp, id=response_id)
        if res.status == res.STATUS_CHOICES[0][0] and res.job.employer.user == request.user:
            res.status = res.STATUS_CHOICES[2][0]
            res.save()
        return redirect('responses_list_view')
    return redirect('home')


@login_required
def responses_list_view(request):
    if request.user.user_type == 'employer':
        resps = resp.objects.filter(job__employer=request.user.id)
        resps = resp.objects.filter(job__employer=request.user.id)
        return render(request, 'jobs/list-of-resps.html', {'resps': resps})
    return redirect('home')


@login_required
def my_resps_view(request):
    print(request.user.user_type)
    if request.user.user_type == 'seeker':
        resps = resp.objects.filter(job_seeker__user=request.user)
        return render(request, 'jobs/myresps.html', {'resps': resps})
    return redirect('home')

# ------------------
# Избранные вакансии
# ------------------


@login_required
def feature_create_view(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    already_featured = False

    if job and not already_featured:
        # print(request.user.id)
        Feature.objects.create(job=job, user=request.user)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def feature_delete(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    feature = get_object_or_404(Feature, job=job, user=request.user)
    feature.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def features_list_view(request):
    if request.user.is_authenticated:
        context = {
            'user_type': request.session.get('user_type'),
            'jobs' : [],
            'responded_jobs': [],
            'feature_jobs': [],
        }
        user_features = Feature.objects.filter(user=request.user)

        cities = user_features.values_list('job__location', flat=True).distinct()
        industries = user_features.values_list('job__industry', flat=True).distinct()
        context['cities'] = cities
        context['industries'] = industries

        if not user_features: 
            user_features = []

        if request.user.user_type == "seeker":
            user_responses = resp.objects.filter(job_seeker=request.user.jobseeker_profile) if hasattr(request.user, 'jobseeker_profile') else []
            responded_jobs = [response.job.id for response in user_responses]
            context['responded_jobs'] = responded_jobs

        featured_jobs = [feature.job.id for feature in user_features]
        context['featured_jobs'] = json.dumps(featured_jobs)

    return render(request, 'jobs/list-of-fts.html', context)


# -------------
# Views для API
# -------------


class JobDetail(RetrieveUpdateDestroyAPIView):
    queryset = Job.objects.all()
    serializer_class = JobSerializer

@api_view(['GET'])
def all_jobs(request):
    jobs = Job.objects.all()
    serializer = JobSerializer(jobs, many=True)
    return Response(serializer.data)


class SkillsDetail(RetrieveUpdateDestroyAPIView):
    queryset = Skill.objects.all()
    serializer_class = SkillsSerializer

@api_view(['GET'])
def all_skills(request):
    skills = Skill.objects.all()
    serializer = SkillsSerializer(skills, many=True)
    return Response(serializer.data)


class ResponseDetail(RetrieveUpdateDestroyAPIView):
    queryset = resp.objects.all()
    serializer_class = ResponseSerializer

@api_view(['GET'])
def all_responses(request):
    jobs = resp.objects.all()
    serializer = ResponseSerializer(jobs, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def all_features(request, pk):
    jobs = Feature.objects.filter(user=pk)
    serializer = FeatureSerializer(jobs, many=True)
    return Response(serializer.data)


class JobListView(generics.ListAPIView):
    serializer_class = JobSerializer

    def get_queryset(self):
        queryset = Job.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
        return queryset

@api_view(['GET'])
def search_jobs(request):

    query = request.GET.get('query')
    if query:
        jobs = jobs.filter(
            Q(title__icontains=query) | Q(description__icontains=query) | Q(employer__company_name__icontains=query)
        )
        
    else:
        query = request.GET.get('q', '')
    
    industry = request.GET.get('industry', '')
    city = request.GET.get('city', '')

    jobs = Job.objects.filter(
        Q(title__icontains=query) | Q(description__icontains=query) | Q(employer__company_name__icontains=query)
    )
    if industry:
        jobs = jobs.filter(industry__iexact=industry)
    if city:
        jobs = jobs.filter(location__iexact=city)

    serializer = JobSerializer(jobs, many=True)
    redirect('home')
    return Response(serializer.data)


@api_view(['GET'])
def search_features(request, pk):
    query = request.GET.get('q', '')
    industry = request.GET.get('industry', '')
    city = request.GET.get('city', '')

    jobs = Feature.objects.filter(user=pk)

    jobs = jobs.filter(
        Q(job__title__icontains=query) | Q(job__description__icontains=query) | Q(job__employer__company_name__icontains=query)
    )
    if industry:
        jobs = jobs.filter(job__industry__iexact=industry)
    if city:
        jobs = jobs.filter(job__location__iexact=city)

    serializer = FeatureSerializer(jobs, many=True)

jobs/templates/jobs/job-details.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}Вакансия | {{ job.title }}{% endblock %}

{% block additionals %}
<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1000;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
    }

    .modal-content {
        background-color: white;
        margin: 15% auto;
        padding: 32px 20px;
        border-radius: 10px;
        width: 80%;
        max-width: 384px;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
</style>
{% endblock %}

{% block content %}
<div class="container white-background" style="box-shadow: none; border-radius: 0;padding: 0;">
    <div style="display: flex;justify-content: space-between;">
        <div class="job-details">
            <div class="job-content vacancy-item" style="text-align:center;">
                <div style="justify-content: space-between;align-items: center;display: flex;margin-top: 12px;">
                    <h1 class="job-title" style="font-size: 28px;margin-top: 0;">{{ job.title }}</h1>
                    <div class="vacancy-side-info">
                        <span style="display:flex;justify-content:end;gap: 8px;min-width: 25%;color:#a3a3a3;"><i class="fi fi-ss-land-layer-location"></i>{{job.location}}</span>
                    </div>
                </div>
                <p class="job-salary" style="margin: 14px 0;">Зарплата: {{ job.salary }}</p>
                <div class="job-info">
                    <p class="job-info-item">Требуемый опыт работы: {{job.work_exp}}</p>
                    <p class="job-info-item">Тип занятости: {{job.get_employment_type_display}}</p>
                    <div style="display: flex;margin-top: 16px;align-items: center;justify-content: left;gap: 12px;">
                        <div class="pulsing-dot red"></div> 
                        <p class="job-info-item">
                            Сейчас эту вакансию смотрят: <span style="color:#ff5454;">{{ job.resps }} чел.</span>
                        </p>
                    </div>
                </div>
                <div class="job-btns-container">
                    <div class="btns-block">
                        {% if user.is_authenticated %}
                            {% if is_featured %}
                                <a class="btn learn-more angles red" href="/jobs/delete/feature/{{job.id}}"><i class="fi fi-ss-heart"></i></a>
                                {% else %}    
                                <a class="btn btn-invert angles" href="/jobs/create/feature/{{job.id}}"><i class="fi fi-ss-heart"></i></a>
                            {% endif %}
                            {% if user_type == 'employer' and is_you %}
                                <a class="btn btn-invert close angles red yellow-alt" href="/jobs/delete/job/{{job.id}}"><i class="fi fi-rr-trash"></i></a>
                            {% endif %}
                            {% if not is_you %}
                                <a class="btn learn-more angles" href="#" style="display: flex;gap: 9px;"><i class="fi fi-ss-comment"></i><span>Перейти к чату</span></a>
                            {% endif %}
                        {% endif %}
                        <a class="btn learn-more angles" href="#" onclick="openModal()">Показать контакты</a>
                    </div>
                    <div id="modal" class="modal">
                        <div class="modal-content" style="position: relative;">
                            <span class="close" onclick="closeModal();" style="position: absolute;top: 24px;right: 24px;">&times;</span>
                            <div>
                                <div class="vacancy-image" style="justify-content: center;margin: 0;">
                                    {% if job.employer.user.profile_picture %}
                                    <img src="{{ job.employer.user.profile_picture.url }}" alt="Фото профиля">
                                    {% else %}
                                    <img src="{% static 'users/images/user_avatar_default.png' %}" alt="Фото профиля">
                                    {% endif %}
                                </div>
                                <div>
                                    <h2 style="color: #555;">Компания {{job.employer.company_name}}<br>Связаться с нами</h2>
                                    <div style="display: flex;justify-content: center;">
                                        <div>
                                            <p style="display: flex;gap: 4px;justify-content: center;"><i style="display: flex;" class="fi fi-br-envelope"></i> {{ job.employer.user.email }}</p>
                                            <p style="display: flex;gap: 4px;justify-content: center;"><i style="display: flex;" class="fi fi-rr-phone-flip"></i> {{ job.employer.user.phone_number }}</p>
                                            <a class="btn learn-more angles" href="#" style="display: flex;gap: 9px;justify-content: space-evenly;margin-top: 32px;"><i class="fi fi-ss-comment"></i><span>Перейти к чату</span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                        var modal = document.getElementById("modal");
                        var closeBtn = document.getElementsByClassName("close")[0];
            
                        function openModal() {
                            modal.style.display = "block";
                        }
            
                        function closeModal() {
                            modal.style.display = "none";
                        }
            
                        window.onclick = function(event) {
                            if (event.target == modal) {
                                modal.style.display = "none";
                            }
                        }
                    </script>
                </div>
            </div>
        </div>
        <div class="company-info vacancy-item">
            <a href="/users/view/company/{{job.employer.user.id}}">
                <div class="vacancy-image" style="justify-content: start;">
                    {% if job.employer.user.profile_picture %}
                    <img src="{{ job.employer.user.profile_picture.url }}" alt="Фото профиля">
                    {% else %}
                    <img src="{% static 'users/images/user_avatar_default.png' %}" alt="Фото профиля">
                    {% endif %}
                </div>
                <p class="comp-name">{{ job.employer.company_name }}</p>
            </a>
            <p class="comp-rating">
                <span style="display: flex;gap: 4px;">
                    <span class="star"></span>
                    <span class="star"></span>
                    <span class="star"></span>
                    <span class="star"></span>
                    <span class="star"></span>
                </span>
                <span id="reviews-quantity" style="font-size: 14px;display: flex;align-items: center;"></span>
                <script>
                    var companyRating = parseFloat('{{ job.employer.rating }}'.replace(',', '.'));
                    var revCount = parseInt('{{ reviews_count }}');
                    var stars = document.getElementsByClassName("star");
                    count = document.getElementById("reviews-quantity");
                    
                    if (companyRating){
                      count.textContent = `(${companyRating.toFixed(2)}) ${revCount} отз.`;
                    }
                    else {
                      count.textContent = "Нет отзывов";
                    }

                    Array.from(stars).forEach((star, index) => {
                        if (companyRating >= index + 1) {
                            // Полная звезда
                            star.innerHTML = `<i class="fi fi-ss-star" style="color: orange;"></i>`;
                        } else if (companyRating > index && companyRating < index + 1) {
                            // Половина звезды
                            star.innerHTML += `<i class="fi fi-ss-star"></i>`;
                            star.innerHTML += `<i class="fi fi-ss-star-sharp-half" style="color: orange;"></i>`;
                        } else {
                          // Пустая звезда
                          star.innerHTML = `<i class="fi fi-ss-star"></i>`;
                        }
                    });
                </script>
            </p>
            <p class="comp-address">{{ job.employer.company_address }}</p>
        </div>
    </div>

    <div style="display: flex;justify-content: space-between;">
        <div class="job-details">
            <div class="job-content vacancy-item">
                <div><h2 class="title" style="color: #555; font-weight: 600;">Описание вакансии</h2></div>
                <div>
                    <p class="description" style="-webkit-line-clamp: unset;">
                        {{ job.description }}
                    </p>
                </div>
                <div class="job-btns-container">
                    <div class="btns-block">
                        <a class="btn learn-more angles" href="/users/view/company/{{job.employer.user.id}}"><i class="fi fi-rr-info"></i></a>
                        {% if user.is_authenticated and user_type == 'seeker' %}
                            {% if responded %}
                                <span class="btn btn-invert green-invert angles">Вы откликнулись</span>
                            {% else %}    
                                <a class="btn btn-invert angles" href="/jobs/create/response/{{job.id }}">Откликнуться</a>
                            {% endif %}    
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="company-info vacancy-item">
            <div style="font-size: 24px;font-weight: 600;color: #555;margin-bottom: 16px;">Требуемые навыки</div>
            <div id="skills-{{job.id}}" style="display: flex;flex-wrap: wrap;gap: 12px;">
                {% for skill in skills %}
                    <span class="alt-info">{{skill.name}}</span>
                {% endfor %}
                {% if not skills %}
                    <span class="alt-info">Нет навыков</span>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

jobs/templates/jobs/list-of-resps.html
{% extends 'users/base.html' %}
{% load static %}
{% block title %}Список откликнувшихся{% endblock %}

{% block additionals %}
{% endblock %}

{% block content %}
<div class="container">
  <div class="vacancy-list" id="vacancy-list">
    {% if not resps %}
    <div class="vacancy-item empty-list">
      <h4>Отклики отсутствуют</h4>
    </div>
    {% else %}
    <ul>
      {% for resp in resps %}
      <li style="display:flex;justify-content:center;">
        <div class="vacancy-item" style="width:65%;">
          <div class="vacancy-main-info">
            <div class="main-side">
              <div class="vacancy-image">
                  {% if resp.job_seeker.user.profile_picture %}
                    <img src="{{ resp.job_seeker.user.profile_picture.url }}" alt="Фото профиля">
                  {% else %}
                    <img src="{% static 'users/images/user_avatar_default.png' %}" alt="Фото профиля">
                  {% endif %}
                </div>
                <div>
                  <p class="item-date">{{ resp.date_of_response }}</p>
                  {% comment %} <h4>{{ resp.job.title }}</h4> {% endcomment %}
                  <p class="company">{{ resp.job_seeker.full_name }}</p>
                </div>
            </div>
            <div class="vacancy-side-info">
              <span style="display: flex;align-items: center;justify-content: right;gap: 12px;font-size: 18px;">
                  {{resp.get_status_display }}
                  {% if resp.status == 'pending' %}
                  <div class="pulsing-dot blue"></div>
                  {% elif resp.status == 'accepted' %}
                  <i style="color: #1bba20;display: flex;align-items: center;" class="fi fi-ss-badge-check"></i>
                  {% else %}
                  <i style="color: #fa4747;display: flex;align-items: center;" class="fi fi-ss-cross-circle"></i>
                  {% endif %}
              </span>
          </div>
          </div>
          <div class="job-btns-container">
            <div class="btns-block">
              <a class="btn btn-invert angles" style="display: flex;gap: 9px;" href="{% url 'job_detail_view' resp.job.id %}"><i class="fi fi-rr-info"></i><span>Подробнее</span></a>
              <a class="btn learn-more angles" style="display: flex;gap: 9px;" href="#"><i class="fi fi-ss-comment"></i><span>Перейти к чату</span></a>
              <a class="btn learn-more green angles" href="{% url 'accept_resp' resp.id %}" style="padding-inline: 14px;display:flex;font-size:20px;"><i class="fi fi-bs-badge-check"></i></a>
              <a class="btn learn-more red angles" href="{% url 'reject_resp' resp.id %}" style="padding-inline: 14px;display:flex;font-size:20px;"><i class="fi fi-bs-cross-circle"></i></a>
            </div>
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock %}